baseNotebook:
  script: docker pull ${OriginalImage} && docker tag ${OriginalImage} ${REGISTRY}/${OWNER}/${ImageName}
  push: docker push ${REGISTRY}/\${OWNER}/\${ImageName}
  params:
    - REGISTRY
    - OWNER
    - ImageName
    - OriginalImage
baseNotebookGpu:
  script: docker build --build-arg BASE_CONTAINER=\${BASE_GPU_RUNTIME} -t \${REGISTRY}/\${OWNER}/\${BaseNotebook}\${GPU}:\${GPUTag} -f \${gitrepo}/\${BaseNotebook}/Dockerfile \${gitrepo}/\${BaseNotebook}
  params:
    - REGISTRY
    - OWNER
    - BaseNotebook
    - BASE_GPU_IMAGE