ARG BASE_CONTAINER=index.alauda.cn/alaudak8s/scipy-notebook-gpu:10.0-cudnn7-runtime
FROM $BASE_CONTAINER

ARG CUDA="cudatoolkit=10.0"

RUN conda install --quiet --yes \
    pytorch torchvision $CUDA -c pytorch && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER && \
    pip install tensorflow tensorboardX jupyter-tensorboard
