ARG BASE_CONTAINER=index.alauda.cn/alaudak8s/scipy-notebook-gpu:10.0-cudnn7-runtime
FROM $BASE_CONTAINER

ARG TF_VERSION=1.13
ARG KERAS_VERSION=2.2

# Install Tensorflow
RUN conda install --quiet --yes \
    'tensorflow-gpu=${TF_VERSION}*' \
    'keras-gpu=${KERAS_VERSION}*' && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER && \
    pip install jupyter-tensorboard