ARG BASE_CONTAINER=index.alauda.cn/alaudak8s/scipy-notebook-gpu:10.0-cudnn7-runtime
FROM $BASE_CONTAINER

TF_VERSION=1.13
KERAS_VERSION=2.2

# Install Tensorflow
RUN conda install --quiet --yes \
    'tensorflow=${TF_VERSION}*' \
    'keras=${KERAS_VERSION}*' && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER