ARG BASE_CONTAINER=index.alauda.cn/alaudak8s/scipy-notebook-gpu:10.0-cudnn7-runtime
FROM ${BASE_CONTAINER}

ARG TF_VERSION=1.13
ARG KERAS_VERSION=2.2

# Install Tensorflow
RUN pip install tensorflow-gpu~=${TF_VERSION} keras~=${KERAS_VERSION} && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER && \
    pip install --pre jupyter-tensorboard
